name: tripview_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.0
  gtfs_realtime_bindings: ^1.2.0
  http: ^1.6.0
  drift: ^2.31.0
  sqlite3: ^3.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  drift_dev: ^2.18.0

flutter:
  uses-material-design: true
  assets:
    - assets/gtfs.db.gz